version: 2

jobs:
  build-job:
    docker:
      - image: termoshtt/mdbook
    steps:
      - checkout
      - run:
          name: Build HTML
          command: |
            mdbook build

  deploy-job:
    docker:
      - image: termoshtt/mdbook
    steps:
      - run:
          name: Deploy to S3
          command: aws s3 sync book/ s3://math-note/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
