version: 2

jobs:
  build:
    docker:
      - image: termoshtt/mdbook
    steps:
      - checkout
      - run:
          name: Build HTML
          command: |
            mdbook build
      - persistent_to_workspace:
          paths:
            - book

  deploy:
    docker:
      - image: termoshtt/mdbook
    steps:
      - run:
          name: Deploy to S3
          command: aws s3 sync book/ s3://math-note/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
